name: Build

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dist-all-packages:
    runs-on: ubuntu-latest

    # Add services for gas station testing
    services:
      gas-station:
        image: twinfoundation/twin-gas-station-test:latest
        ports:
          - 6379:6379
          - 9527:9527
          - 9184:9184
        # Health check to ensure gas station is ready
        options: >-
          --health-cmd "curl -f http://localhost:9527 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Add env vars for tests
    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}

    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Setup test environment (IOTA CLI + Gas Station)
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-environment

      # Run tests explicitly for better CI feedback
      - name: Run Tests
        run: |
          # Run tests for packages that have gas station integration
          cd packages/nft-connector-iota && npm test

      # Run Lint and Dist
      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
