name: Build

on:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  dist-all-packages:
    runs-on: ubuntu-latest

    # Add services for gas station testing
    services:
      gas-station:
        image: twinfoundation/twin-gas-station-test:latest
        ports:
          - 6379:6379
          - 9527:9527
          - 9184:9184
        # Health check to ensure gas station is ready
        options: >-
          --health-cmd "curl -f http://localhost:9527 || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Add env vars for tests
    env:
      TEST_MNEMONIC: ${{ secrets.TEST_MNEMONIC }}
      TEST_2_MNEMONIC: ${{ secrets.TEST_2_MNEMONIC }}
      TEST_NODE_MNEMONIC: ${{ secrets.TEST_NODE_MNEMONIC }}
      # Gas Station configuration
      GAS_STATION_URL: http://localhost:9527
      GAS_STATION_AUTH_TOKEN: qEyCL6d9BKKFl/tfDGAKeGFkhUlf7FkqiGV7Xw4JUsI=
      GAS_BUDGET: 50000000

    steps:
      # Get the code
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Setup any services required for tests here
      - name: Download IOTA CLI
        run: |
          wget https://github.com/iotaledger/iota/releases/download/v1.0.0/iota-v1.0.0-linux-x86_64.tgz -O iota-cli.tgz
          tar xzf iota-cli.tgz
          rm iota-cli.tgz
          chmod +x iota
          sudo mv iota /usr/local/bin/iota
          iota --version

      # Verify gas station is ready
      - name: Wait for Gas Station
        run: |
          echo "Waiting for gas station to be ready..."
          timeout 60 bash -c 'until curl -f http://localhost:9527; do sleep 2; done'
          echo "Gas station is ready!"

      # Run Lint and Dist
      - name: Run Lint and Dist
        run: |
          npm run lint
          npm run dist
